version: '2'

services:
  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: ["agent", "-dev", "-log-level=debug", "-client", "0.0.0.0"]
  api-v1:
    image: amitsaha/api:v1
    depends_on:
      - consul
  api-v2:
    image: amitsaha/api:v2
    depends_on:
      - consul
