version: '2'

services:
  consul:
    networks:
      consul_demo: {}
    image: consul
    container_name: consul
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: ["agent", "-dev", "-log-level=debug", "-client", "0.0.0.0"]
  api-v1:
    networks:
      consul_demo: {}
    image: amitsaha/api:v1
    depends_on:
      - consul
    ports:
      - 8080:8080
  api-v2:
    networks:
      consul_demo: {}
    image: amitsaha/api:v2
    depends_on:
      - consul
    ports:
      - 8081:8080
  dnsmasq:
    networks:
      consul_demo: {}
    image: amitsaha/dnsmasq
    depends_on:
      - consul
    ports:
      - 53:53/udp
    cap_add:
      - NET_ADMIN
networks:
  consul_demo:
    driver: bridge
