version: '2'

services:
  consul:
    networks:
      consul_demo: {}
    image: consul
    container_name: consul
    command: ["agent", "-dev", "-log-level=debug", "-client", "0.0.0.0"]
  api-v1:
    networks:
      consul_demo: {}
    image: amitsaha/api:v1
    depends_on:
      - consul
  api-v2:
    networks:
      consul_demo: {}
    image: amitsaha/api:v2
    depends_on:
      - consul
networks:
  consul_demo:
    driver: bridge
